apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bestrong-api-metrics
  namespace: monitoring
  labels:
    app: bestrong-api
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: bestrong-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
